sudo: required
node_js:
  - "10"
services:
  - docker

before_install:
  - docker build -t brightside67/docker-react -f Dockerfile.dev .

script:
  - docker run brightside67/docker-react npm run test -- --coverage --forceExit --maxWorkers=10
